create table if not exists public.volunteer_opportunities (
  id text primary key,
  data jsonb not null,
  organization text generated always as (data ->> 'organization') stored,
  town text generated always as (data ->> 'town') stored,
  category text generated always as (data ->> 'category') stored,
  teen_friendly boolean generated always as ((data ->> 'teenFriendly')::boolean) stored,
  needs_verification boolean generated always as ((data ->> 'needsVerification')::boolean) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.volunteer_opportunities enable row level security;

drop policy if exists "Anyone can read volunteer opportunities"
on public.volunteer_opportunities;

create policy "Anyone can read volunteer opportunities"
on public.volunteer_opportunities
for select
to anon, authenticated
using (true);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_volunteer_opportunities_updated_at
on public.volunteer_opportunities;

create trigger set_volunteer_opportunities_updated_at
before update on public.volunteer_opportunities
for each row execute procedure public.set_updated_at();

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view', 'click')),
  path text not null,
  label text,
  href text,
  session_id text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.site_events enable row level security;

drop policy if exists "Anyone can insert site events"
on public.site_events;

create policy "Anyone can insert site events"
on public.site_events
for insert
to anon, authenticated
with check (true);

drop policy if exists "Anyone can read site events"
on public.site_events;

create index if not exists site_events_created_at_idx
on public.site_events (created_at desc);

create index if not exists site_events_event_type_idx
on public.site_events (event_type);

create index if not exists site_events_path_idx
on public.site_events (path);
