export type OpportunityDuration =
  | "One-time"
  | "Ongoing"
  | "One-time and ongoing"
  | "Contact organization";

export type VolunteerOpportunity = {
  id: string;
  organization: string;
  town: string;
  category: string;
  description: string;
  ageDisplay: string;
  minimumAge: number | null;
  requirements: string[];
  schedule: string[];
  volunteerUrl: string | null;
  applicationUrl: string | null;
  notes: string[];
  teenFriendly: boolean;
  weekend: boolean;
  duration: OpportunityDuration;
  needsVerification: boolean;
  tags: string[];
};

export const opportunities: VolunteerOpportunity[] = [
  {
    id: "closter-nature-center",
    organization: "Closter Nature Center",
    town: "Closter",
    category: "Environment",
    description:
      "Help maintain trails, restore habitats, assist with educational programs, and support community events at a local nature preserve.",
    ageDisplay: "Minimum age: 13 (depending on what you choose to volunteer in)",
    minimumAge: 13,
    requirements: ["Adult opportunities as well"],
    schedule: ["One-time", "Ongoing", "Weekend"],
    volunteerUrl: "https://www.closternaturecenter.org/volunteer",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: true,
    duration: "One-time and ongoing",
    needsVerification: false,
    tags: ["Age 13+", "Weekend", "Ongoing", "One-time"]
  },
  {
    id: "closter-volunteer-ambulance-and-rescue-corps",
    organization: "Closter Volunteer Ambulance and Rescue Corps",
    town: "Closter",
    category: "Healthcare",
    description:
      "Receive emergency response training and assist with ambulance services, community events, and public safety initiatives.",
    ageDisplay: "Cadet volunteering for students; above 18, volunteers apply",
    minimumAge: null,
    requirements: [
      "Resident of Closter or bordering town",
      "Cadet volunteering application provides students with cadet training and volunteer hours"
    ],
    schedule: ["Few hours of service a week", "Ongoing", "Weekend"],
    volunteerUrl: null,
    applicationUrl: null,
    notes: ["Original category listed as Healthcare", "Needs verification"],
    teenFriendly: true,
    weekend: true,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Age varies", "Weekend", "Ongoing", "Training"]
  },
  {
    id: "claws",
    organization: "CLAWS",
    town: "Closter",
    category: "Animals",
    description:
      "Care for cats, clean enclosures, socialize animals, assist with adoption events, and help animals find permanent homes.",
    ageDisplay: "Typically 16+",
    minimumAge: 16,
    requirements: [],
    schedule: ["One-time", "Ongoing", "Weekend"],
    volunteerUrl:
      "http://njclaws.squarespace.com/Volunteer/;jsessionid=58514ED6DF96F47B718293ECC78AC641.v5-web001",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: true,
    duration: "One-time and ongoing",
    needsVerification: false,
    tags: ["Age 16+", "Weekend", "Ongoing", "One-time"]
  },
  {
    id: "spectrum-for-living-closter",
    organization: "Spectrum for Living",
    town: "Closter",
    category: "Food Assistance",
    description:
      "Help organize, sort, and distribute food to local families. Volunteer opportunities are generally available during distribution days.",
    ageDisplay: "16+",
    minimumAge: 16,
    requirements: ["Need 2 references"],
    schedule: ["At least 25 hours a year"],
    volunteerUrl: "https://spectrumforliving.org/volunteer/",
    applicationUrl: null,
    notes: ["Needs verification: source description mentions food distribution"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 16+", "References", "25 hours/year", "Needs verification"]
  },
  {
    id: "closter-public-library",
    organization: "Closter Public Library",
    town: "Closter",
    category: "Library",
    description:
      "Assist librarians with children's programs, summer reading activities, organizing materials, setting up events, and other library projects while earning community service hours. Volunteer spots are offered periodically and may fill quickly.",
    ageDisplay: "Ages 15-18",
    minimumAge: 15,
    requirements: [],
    schedule: ["Offered periodically", "Volunteer spots may fill quickly"],
    volunteerUrl:
      "https://www.closterpubliclibrary.org/online-programs-resources-y-adults",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Ages 15-18", "Periodic"]
  },
  {
    id: "closter-environmental-commission",
    organization: "Closter Environmental Commission",
    town: "Closter",
    category: "Environment",
    description:
      "Participate in environmental initiatives, community cleanups, tree planting, educational events, and sustainability projects throughout the borough.",
    ageDisplay: "All ages; students and adults",
    minimumAge: null,
    requirements: [],
    schedule: ["One-time", "Ongoing", "Weekend"],
    volunteerUrl: null,
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: true,
    duration: "One-time and ongoing",
    needsVerification: true,
    tags: ["All ages", "Weekend", "Ongoing", "One-time"]
  },
  {
    id: "closter-food-pantry",
    organization: "Closter Food Pantry",
    town: "Closter",
    category: "Food Assistance",
    description:
      "Sort donations, pack food, and distribute groceries to local families experiencing food insecurity.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them to volunteer"],
    schedule: ["Hosting food drives"],
    volunteerUrl: "https://www.closterboro.com/page/food-and-assistance-board",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Food drives", "Contact organization"]
  },
  {
    id: "demarest-nature-center",
    organization: "Demarest Nature Center",
    town: "Demarest",
    category: "Environment",
    description:
      "Help maintain trails, remove invasive plants, assist with educational programs, lead nature walks, and support community events at the 55-acre nature preserve.",
    ageDisplay: "13+ (some roles); 18+ (leadership)",
    minimumAge: 13,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.demarestnaturecenter.org/support/volunteer.html",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 13+", "18+ leadership", "Nature preserve"]
  },
  {
    id: "demarest-volunteer-ambulance-corps",
    organization: "Demarest Volunteer Ambulance Corps",
    town: "Demarest",
    category: "Healthcare",
    description:
      "Train to assist with emergency medical services, become an EMT, or volunteer as a driver or support member. Free training is provided, and students are encouraged to join.",
    ageDisplay: "16+",
    minimumAge: 16,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: "https://demarestnj.gov/departments/ems",
    applicationUrl: null,
    notes: ["Good for at-home moms and dads as well as retirees"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 16+", "Training", "Students encouraged"]
  },
  {
    id: "demarest-fire-department",
    organization: "Demarest Fire Department",
    town: "Demarest",
    category: "Public Safety",
    description:
      "Volunteer firefighters help respond to emergencies, participate in training, and support fire prevention and community safety programs.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: null,
    applicationUrl: null,
    notes: ["Needs verification"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Training", "Needs verification"]
  },
  {
    id: "demarest-free-public-library",
    organization: "Demarest Free Public Library",
    town: "Demarest",
    category: "Library",
    description:
      "TAB - Teen Advisory Board. Inspire and motivate teens to become regular library users. Support and facilitate programs for children within their community.",
    ageDisplay: "Teens, 14+",
    minimumAge: 14,
    requirements: ["Residents of Demarest"],
    schedule: ["Monthly meetings"],
    volunteerUrl: "https://www.demarestlibrary.org/youth/tab/",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 14+", "Teen Advisory Board", "Monthly"]
  },
  {
    id: "the-art-school-at-old-church",
    organization: "The Art School at Old Church",
    town: "Demarest",
    category: "Arts",
    description:
      "A nonprofit art school that periodically welcomes volunteers to help with exhibitions, community events, and arts programming. Contact the school for current opportunities.",
    ageDisplay: "Volunteers 15+ can be camp assistants",
    minimumAge: 15,
    requirements: [],
    schedule: ["Periodically welcomes volunteers", "Contact the school for current opportunities"],
    volunteerUrl: "https://www.tasoc.org/opportunities",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 15+", "Camp assistants", "Arts"]
  },
  {
    id: "haworth-ambulance-volunteer-corps",
    organization: "Haworth Ambulance Volunteer Corps",
    town: "Haworth",
    category: "Healthcare",
    description:
      "Receive free emergency medical training and help respond to emergency calls, assist with community events, and provide medical services to Haworth residents.",
    ageDisplay:
      "16-18 junior membership enrollment; first responder emergency training - 18 years old; drivers - 21+ years old",
    minimumAge: 16,
    requirements: [
      "Junior membership enrollment",
      "Train at local EMS facility (Paramus, Teterboro, or Mahwah)",
      "Drivers must be 21+ years old, have a clean record, and help lift patients and equipment"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.haworthnj.org/ambulance",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 16+", "Training", "Drivers 21+"]
  },
  {
    id: "haworth-volunteer-fire-department",
    organization: "Haworth Volunteer Fire Department",
    town: "Haworth",
    category: "Public Safety",
    description:
      "Help protect the community through firefighting, emergency response, fire prevention, and community outreach. Junior members train alongside experienced firefighters.",
    ageDisplay:
      "Ages 18-65 (training included); Junior Fire Department: teens 14-17",
    minimumAge: 14,
    requirements: ["Training included"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.haworthnj.org/fire",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Teens 14-17", "Adults 18-65", "Training"]
  },
  {
    id: "haworth-municipal-library",
    organization: "Haworth Municipal Library",
    town: "Haworth",
    category: "Library",
    description:
      "Speak to the library director or children's librarian about opportunities.",
    ageDisplay: "Age varies; middle school students through adults",
    minimumAge: null,
    requirements: ["Speak to the library director or children's librarian"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.haworthlibrary.org/volunteer",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Middle schoolers", "Contact organization"]
  },
  {
    id: "borough-of-haworth-boards-commissions-and-committees",
    organization: "Borough of Haworth Boards, Commissions and Committees",
    town: "Haworth",
    category: "Civic",
    description:
      "Serve on town committees or assist with borough initiatives involving recreation, environmental projects, planning, and other community programs.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: "https://ecode360.com/35567810",
    applicationUrl: null,
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 18+", "Boards", "Committees"]
  },
  {
    id: "haworth-police-auxiliary",
    organization: "Haworth Police Auxiliary",
    town: "Haworth",
    category: "Public Safety",
    description:
      "Contact them to volunteer with the Haworth Police Auxiliary.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Contact them to volunteer"],
    schedule: ["Contact organization"],
    volunteerUrl:
      "https://haworthpd.org/index.asp?SEC=AED0D236-8BA2-4164-A8DD-A79AD3878E32&DE=F53D1725-DD59-47F7-BFCD-F4B5F9BF6B1D",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 18+", "Contact organization"]
  },
  {
    id: "sacred-heart-church",
    organization: "Sacred Heart Church",
    town: "Haworth",
    category: "Faith-Based",
    description:
      "Teens can often volunteer at parish events, food drives, holiday programs, and community outreach. Opportunities depend on the season.",
    ageDisplay: "Teens can often volunteer",
    minimumAge: null,
    requirements: ["Contact them to volunteer"],
    schedule: ["Opportunities depend on the season"],
    volunteerUrl: "https://sacredhearthaworth.com/volunteer-opportunities",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Seasonal", "Food drives"]
  },
  {
    id: "dixon-homestead-library",
    organization: "Dixon Homestead Library",
    town: "Dumont",
    category: "Library",
    description:
      "Help organize books, assist with children's crafts and programs, and support library events. Teen volunteers are accepted from Dumont residents.",
    ageDisplay: "14-17 teen volunteering opportunity",
    minimumAge: 14,
    requirements: ["Teen volunteers are accepted from Dumont residents"],
    schedule: ["No more than 3 hours a week for volunteers"],
    volunteerUrl:
      "https://www.dumontlibrary.org/dixon-homestead-library-children-section-events",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Ages 14-17", "Dumont residents", "3 hours/week"]
  },
  {
    id: "dumont-volunteer-ambulance-corps",
    organization: "Dumont Volunteer Ambulance Corps",
    town: "Dumont",
    category: "Healthcare",
    description:
      "Train to become an EMT or support the corps through auxiliary and community service roles. Free training is available for eligible volunteers.",
    ageDisplay: "Age varies; students and adults can volunteer",
    minimumAge: null,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.dumontambulance.org/join-us/",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age varies", "Students", "Training"]
  },
  {
    id: "dumont-volunteer-fire-department",
    organization: "Dumont Volunteer Fire Department",
    town: "Dumont",
    category: "Public Safety",
    description:
      "Volunteer firefighters help protect the community through emergency response, training, fire prevention, and public education.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Fill out form to join"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.dumontfire.org/join-dfd",
    applicationUrl: "https://www.dumontfire.org/join-dfd",
    notes: ["Needs verification"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Form", "Needs verification"]
  },
  {
    id: "dumont-social-services",
    organization: "Dumont Social Services",
    town: "Dumont",
    category: "Social Services",
    description:
      "Help with seasonal food drives, holiday gift programs, clothing donations, and assistance for families in need. Many opportunities are available during the holiday season.",
    ageDisplay: "Age 18+",
    minimumAge: null,
    requirements: ["Apply by filling out a form"],
    schedule: ["Many opportunities are available during the holiday season"],
    volunteerUrl: "https://www.dumontnj.gov/volunteer",
    applicationUrl: "https://www.dumontnj.gov/volunteer",
    notes: ["Needs verification"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 18+", "Seasonal", "Food drives", "Needs verification"]
  },
  {
    id: "dumont-shade-tree-commission",
    organization: "Dumont Shade Tree Commission",
    town: "Dumont",
    category: "Environment",
    description:
      "Residents can participate in tree-planting and events and can still gain hours.",
    ageDisplay: "Age 18+",
    minimumAge: null,
    requirements: ["No volunteer application"],
    schedule: ["Tree-planting and events"],
    volunteerUrl: null,
    applicationUrl: null,
    notes: ["Needs verification"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 18+", "Tree planting", "No application"]
  },
  {
    id: "the-food-brigade-inc-dumont",
    organization: "The Food Brigade Inc.",
    town: "Dumont",
    category: "Food Assistance",
    description:
      "Help collect, sort, and distribute food to local families experiencing food insecurity through community outreach and food assistance programs.",
    ageDisplay: "Age varies; high school students, retired adults, and at-home parents",
    minimumAge: null,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: "https://foodbrigade.org/volunteer",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["All ages", "High school", "Food assistance"]
  },
  {
    id: "old-tappan-volunteer-first-aid-corps",
    organization: "Old Tappan Volunteer First Aid Corps",
    town: "Old Tappan",
    category: "Healthcare",
    description:
      "Train as an EMT or volunteer with the First Aid Corps to respond to emergencies, gain medical experience, and earn community service hours. Free training is provided.",
    ageDisplay: "16 years or older",
    minimumAge: 16,
    requirements: ["Time commitment for EMT training before beginning actual volunteering"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.oldtappan.net/departments/ems",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 16+", "EMT training", "Community service hours"]
  },
  {
    id: "old-tappan-volunteer-fire-department",
    organization: "Old Tappan Volunteer Fire Department",
    town: "Old Tappan",
    category: "Public Safety",
    description:
      "Assist with firefighting, emergency response, fire prevention, and community events as part of the volunteer fire department.",
    ageDisplay:
      "Cadet firefighters: 15; junior firefighters: 16-18; probationary firefighters: 18-55; up to 65 if 10 years prior service experience with other department",
    minimumAge: 15,
    requirements: ["Must be physically fit"],
    schedule: ["Contact organization"],
    volunteerUrl: null,
    applicationUrl:
      "https://www.oldtappan.net/images/OTFD/OT_Fire_Department_Application.pdf",
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 15+", "Junior firefighters", "Application PDF"]
  },
  {
    id: "northvale-volunteer-ambulance-corps",
    organization: "Northvale Volunteer Ambulance Corps",
    town: "Northvale",
    category: "Healthcare",
    description:
      "Train as an EMT or First Responder and help provide emergency medical care to Northvale and neighboring communities. No prior experience is required, and training is provided.",
    ageDisplay: "NVAC Youth Squad: 15+, begin answering calls at 16",
    minimumAge: 15,
    requirements: ["No prior experience is required", "Training is provided"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.northvaleambulancecorps.com/",
    applicationUrl: "https://www.northvaleambulancecorps.com/pdf/nvac_application.pdf",
    notes: ["Downloaded application"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 15+", "Youth squad", "Application PDF", "Training"]
  },
  {
    id: "northvale-volunteer-fire-department",
    organization: "Northvale Volunteer Fire Department",
    town: "Northvale",
    category: "Public Safety",
    description:
      "Volunteer firefighters respond to fires, rescues, and emergencies while participating in training and community outreach. All training and equipment are provided.",
    ageDisplay: "Ages: 18-57",
    minimumAge: 18,
    requirements: [
      "Citizen of the U.S.",
      "Resident of the State of New Jersey",
      "Reside in Northvale or one of the surrounding towns, including Closter, Harrington Park, Norwood, Rockleigh, or Old Tappan"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://northvalevfd.org/volunteer/",
    applicationUrl: null,
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Ages 18-57", "Resident requirement", "Training"]
  },
  {
    id: "northvale-public-library",
    organization: "Northvale Public Library",
    town: "Northvale",
    category: "Library",
    description:
      "Assist with children's programs, summer reading, library events, and organizing materials. Contact the library for current teen volunteer opportunities.",
    ageDisplay: "Any ages, middle school and high school probably preferred",
    minimumAge: null,
    requirements: [],
    schedule: ["Contact the library for current teen volunteer opportunities"],
    volunteerUrl: "https://www.northvalelibrary.org/teen-programs",
    applicationUrl: null,
    notes: ["Needs verification"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Middle school", "High school"]
  },
  {
    id: "spectrum-for-living-northvale",
    organization: "Spectrum for Living",
    town: "Northvale",
    category: "Disability Services",
    description:
      "Support adults with developmental disabilities through recreational activities, community outings, and special events.",
    ageDisplay: "16+",
    minimumAge: 16,
    requirements: [
      "Able to commit to regular schedule",
      "Requirements like references and record search"
    ],
    schedule: ["Regular schedule"],
    volunteerUrl: "https://spectrumforliving.org/volunteer/",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 16+", "Regular schedule", "References", "Record search"]
  },
  {
    id: "st-anthonys-roman-catholic-church",
    organization: "St. Anthony's Roman Catholic Church",
    town: "Northvale",
    category: "Faith-Based",
    description:
      "Volunteer for food drives, parish events, holiday outreach, youth ministry, and community service projects throughout the year.",
    ageDisplay: "Age varies; teens and adults",
    minimumAge: null,
    requirements: [],
    schedule: ["Throughout the year"],
    volunteerUrl: null,
    applicationUrl:
      "https://docs.google.com/forms/d/e/1FAIpQLSdqaEMBGg2f_l7XMI1b9aC0DXSefzT6kA4mFgixN9WlY6Yk7g/viewform?fbzx=9130077530110925732",
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age varies", "Teens", "Food drives", "Form"]
  },
  {
    id: "morrill-memorial-library",
    organization: "Morrill Memorial Library",
    town: "Norwood",
    category: "Library",
    description:
      "Help in the Children's Department by shelving books, preparing crafts, setting up programs, cleaning displays, and assisting with library events. Volunteers commit to one 2-hour shift per week.",
    ageDisplay: "Student volunteers: 12+",
    minimumAge: 12,
    requirements: ["Self-motivated and positive attitude", "Speak English well"],
    schedule: ["One 2-hour shift per week"],
    volunteerUrl: "https://norwoodlibrary.org/youth-volunteering/",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 12+", "Students", "2 hours/week"]
  },
  {
    id: "norwood-fire-department",
    organization: "Norwood Fire Department",
    town: "Norwood",
    category: "Public Safety",
    description:
      "Volunteer firefighters respond to emergencies, participate in training, and help with community events like the Easter Egg Hunt, Halloween Parade, and Tree Lighting.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Stop at the warehouse to ask to volunteer"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://norwoodfd.org/",
    applicationUrl: null,
    notes: ["Needs verification"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Training", "Contact organization"]
  },
  {
    id: "norwood-volunteer-ambulance-corps",
    organization: "Norwood Volunteer Ambulance Corps",
    town: "Norwood",
    category: "Healthcare",
    description:
      "Volunteer as an EMT or support member, helping provide emergency medical services to Norwood residents.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact borough to volunteer"],
    schedule: ["Contact organization"],
    volunteerUrl: null,
    applicationUrl: null,
    notes: ["No working website as of now", "Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Contact borough", "Needs verification"]
  },
  {
    id: "the-church-of-the-holy-communion",
    organization: "The Church of the Holy Communion",
    town: "Norwood",
    category: "Faith-Based",
    description:
      "Volunteer with the food pantry by contacting the organization.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Volunteer by contacting the organization"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.holycommunionnorwood.com/food-pantry/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Food pantry", "Contact organization"]
  },
  {
    id: "harrington-park-volunteer-ambulance-corps",
    organization: "Harrington Park Volunteer Ambulance Corps",
    town: "Harrington Park",
    category: "Healthcare",
    description:
      "Train as an EMT, First Responder, driver, or support member while providing emergency medical services to Harrington Park and neighboring towns. Free training is provided.",
    ageDisplay: "16+ for some roles, 18+ for others",
    minimumAge: 16,
    requirements: [
      "Requirements for juniors: https://81b714ff-04c6-483c-9933-33563c78e185.filesusr.com/ugd/bf3c1f_e3c33ecc5d6f466f9791b70c14574f50.pdf"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.hpambulance.org/join-the-corps",
    applicationUrl:
      "https://81b714ff-04c6-483c-9933-33563c78e185.filesusr.com/ugd/bf3c1f_e3c33ecc5d6f466f9791b70c14574f50.pdf",
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 16+", "18+ some roles", "Free training", "Junior requirements"]
  },
  {
    id: "harrington-park-fire-department",
    organization: "Harrington Park Fire Department",
    town: "Harrington Park",
    category: "Public Safety",
    description:
      "Volunteer firefighters respond to emergencies, complete regular training, and participate in community outreach and public safety events.",
    ageDisplay: "Typically 16-18+",
    minimumAge: 16,
    requirements: ["Contact them"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://hpfire.org/become-a-member/",
    applicationUrl: null,
    notes: ["Needs verification"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 16+", "Training", "Contact organization"]
  },
  {
    id: "harrington-park-public-library",
    organization: "Harrington Park Public Library",
    town: "Harrington Park",
    category: "Library",
    description:
      "Help with library programs, community events, and special projects. The library also welcomes volunteers for its ESL tutoring program and other activities.",
    ageDisplay: "Age varies; teens and adults",
    minimumAge: null,
    requirements: ["Contact them or go to the library to sign up"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.harringtonpark.bccls.org/adults",
    applicationUrl: null,
    notes: ["Source listed this as Harrington Park Fire Department; needs verification"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Teens", "ESL tutoring", "Needs verification"]
  },
  {
    id: "our-lady-of-victories-church",
    organization: "Our Lady of Victories Church",
    town: "Harrington Park",
    category: "Faith-Based",
    description: "Contact Our Lady of Victories Church to volunteer.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact to volunteer"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://olvhp.org/contact-us",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Contact organization"]
  },
  {
    id: "community-church-in-harrington-park",
    organization: "Community Church in Harrington Park",
    town: "Harrington Park",
    category: "Faith-Based",
    description: "Contact Community Church in Harrington Park to volunteer.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them to volunteer"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://cchpchurch.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Contact organization"]
  },
  {
    id: "bergenfield-public-library-junior-library-council",
    organization: "Bergenfield Public Library - Junior Library Council",
    town: "Bergenfield",
    category: "Library",
    description:
      "Help with library activities and service projects through teen summer volunteering and the Junior Library Council.",
    ageDisplay: "Grades 6-12; only open for Bergenfield residents in grades 8-12",
    minimumAge: null,
    requirements: [
      "Enrollment to the Junior Library Council",
      "Only open for Bergenfield residents in grades 8-12",
      "Enroll using Google Form",
      "5 minute grace period for attending meetings"
    ],
    schedule: ["Monthly meetings mandatory"],
    volunteerUrl: "https://www.bergenfieldlibrary.org/junior-library-council-jlc/",
    applicationUrl: null,
    notes: ["Needs verification: grade eligibility wording lists grades 6-12 and Bergenfield residents in grades 8-12"],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Grades 6-12", "Bergenfield residents", "Monthly meetings", "Google Form"]
  },
  {
    id: "bergenfield-public-library-esl",
    organization: "Bergenfield Public Library ESL",
    town: "Bergenfield",
    category: "Education",
    description:
      "Work one-on-one or with small groups to help adults in the community learn English. Tutors may also lead conversation classes.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Fill out form", "10 hour training workshop and homework needed"],
    schedule: ["Minimum of 60 minutes per week"],
    volunteerUrl: "https://www.bergenfieldlibrary.org/become-a-tutor/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Age varies", "ESL", "Training", "60 minutes/week"]
  },
  {
    id: "bergenfield-friends-program",
    organization: "Bergenfield Friends Program",
    town: "Bergenfield",
    category: "Library",
    description:
      "Support library programs and help deliver library materials to homebound residents through the Outreach Program.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them to join"],
    schedule: ["Mandatory meeting on the 1st Thursday of each month besides July at 12:30 PM"],
    volunteerUrl: "https://www.bergenfieldlibrary.org/friends-of-the-bf-library/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Age varies", "Monthly meetings", "Outreach Program"]
  },
  {
    id: "bergenfield-volunteer-ambulance",
    organization: "Bergenfield Volunteer Ambulance",
    town: "Bergenfield",
    category: "Healthcare",
    description:
      "Join Bergenfield's nonprofit volunteer emergency ambulance service and help provide emergency medical care to the community.",
    ageDisplay: "At least 16 years of age; full active members are 18",
    minimumAge: 16,
    requirements: [
      "No prior training needed",
      "Do not need to be a Bergenfield resident, but the organization limits the percentage of out-of-town members accepted"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.bergenfieldambulance.org/",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 16+", "Full active 18+", "Training provided"]
  },
  {
    id: "bergenfield-boards-and-committees",
    organization: "Bergenfield Boards and Committees",
    town: "Bergenfield",
    category: "Civic",
    description:
      "Residents may serve the borough through groups involving environmental issues, public health, accessibility, emergency planning, recreation, and other community matters.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Contact by mail by scanning codes"],
    schedule: ["Multiple different kinds of volunteering"],
    volunteerUrl: "https://bergenfieldnj.gov/boards/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 18+", "Boards", "Committees"]
  },
  {
    id: "bergenfield-environmental-committee",
    organization: "Bergenfield Environmental Committee",
    town: "Bergenfield",
    category: "Environment",
    description:
      "Participate in local environmental planning and projects through the borough's Environmental Committee.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Join by form and mail"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://bergenfieldnj.gov/boards/environmental-committee/",
    applicationUrl: null,
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 18+", "Environment", "Mail form"]
  },
  {
    id: "bergenfield-shade-tree-committee",
    organization: "Bergenfield Shade Tree Committee",
    town: "Bergenfield",
    category: "Environment",
    description:
      "Support efforts to preserve Bergenfield's tree canopy, promote healthy landscapes, and beautify public spaces.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Join by mail"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://bergenfieldnj.gov/boards/shade-tree-committee/",
    applicationUrl: null,
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 18+", "Trees", "Beautification"]
  },
  {
    id: "cresskill-fire-department",
    organization: "Cresskill Fire Department",
    town: "Cresskill",
    category: "Public Safety",
    description:
      "Join the Volunteer Fire Division or EMS Division to receive professional training and help respond to emergencies and community events. Applications are accepted year-round.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Email them"],
    schedule: ["Applications are accepted year-round"],
    volunteerUrl: "https://www.cresskillboro.com/departments/fire",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Age 18+", "Training", "Year-round"]
  },
  {
    id: "cresskill-public-library-friends",
    organization: "Cresskill Public Library - Friends",
    town: "Cresskill",
    category: "Library",
    description:
      "Join the Friends of the Library to support library programs, fundraising events, museum passes, and community activities. The library also has a High School Friends group.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them", "Must donate $25 cash or check"],
    schedule: [
      "Monthly meetings every 3rd Wednesday at 7 PM",
      "Registration starts August 2026 and ends 9/18"
    ],
    volunteerUrl: "https://www.cresskilllibrary.org/support-us",
    applicationUrl: null,
    notes: ["Needs verification: registration end date year not specified"],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Age varies", "High School Friends", "Monthly meetings"]
  },
  {
    id: "cresskill-public-library",
    organization: "Cresskill Public Library",
    town: "Cresskill",
    category: "Library",
    description:
      "Volunteer with library events, youth activities, and community programs. Contact the library for current volunteer opportunities.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact the library to help"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.cresskilllibrary.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Library events", "Youth activities"]
  },
  {
    id: "saint-therese-of-lisieux",
    organization: "Saint Therese of Lisieux",
    town: "Cresskill",
    category: "Faith-Based",
    description:
      "Help with food drives, meal programs, homeless outreach, Family Promise projects, and other community service initiatives.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.sttheresecresskill.org/contact-us",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Food drives", "Outreach"]
  },
  {
    id: "tenafly-nature-center",
    organization: "Tenafly Nature Center",
    town: "Tenafly",
    category: "Environment",
    description:
      "Volunteer as an animal caretaker, trail steward, office assistant, photographer, or event helper. Training is provided, and both student and adult opportunities are available.",
    ageDisplay: "14+ some roles, 18+ some roles",
    minimumAge: 14,
    requirements: ["Submit application through Bergen Volunteer for Tenafly Nature Center"],
    schedule: ["Volunteer opportunities limited"],
    volunteerUrl: "https://tenaflynaturecenter.org/volunteer-opportunities/",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 14+", "18+ some roles", "Training", "Limited openings"]
  },
  {
    id: "tenafly-public-library",
    organization: "Tenafly Public Library",
    town: "Tenafly",
    category: "Library",
    description:
      "Volunteer through Reading Buddies, Adopt a Shelf, Teen Advisory Group, or as a Program Assistant helping with children's events and activities.",
    ageDisplay: "Teens and tweens, 6th grade and up",
    minimumAge: null,
    requirements: ["Fill out the teen volunteer form"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.tenaflylibrary.org/teen-volunteers",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["6th grade+", "Reading Buddies", "Teen Advisory Group"]
  },
  {
    id: "tenafly-volunteer-ambulance-corps",
    organization: "Tenafly Volunteer Ambulance Corps",
    town: "Tenafly",
    category: "Healthcare",
    description:
      "Volunteer as an EMT, driver, or support member. Training is provided, and applicants must live in Tenafly or a neighboring town.",
    ageDisplay: "16+",
    minimumAge: 16,
    requirements: ["Contact through the borough/TVAC", "Must live in Tenafly or a neighboring town"],
    schedule: ["Contact organization"],
    volunteerUrl: null,
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 16+", "Training", "Neighboring town"]
  },
  {
    id: "tenafly-volunteer-fire-department",
    organization: "Tenafly Volunteer Fire Department",
    town: "Tenafly",
    category: "Public Safety",
    description:
      "Volunteer firefighters respond to emergencies, complete training, and participate in community fire prevention and outreach programs.",
    ageDisplay: "Cadet/junior: ages 14-18; regular member age varies",
    minimumAge: 14,
    requirements: [
      "Contact department",
      "To become a cadet/junior, contact 201-568-9269",
      "Become a regular member by contacting the same number"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.tenaflynj.gov/201/Fire-Department",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 14+", "Cadet/junior", "Training"]
  },
  {
    id: "volunteer-petresq",
    organization: "Volunteer PetResQ",
    town: "Tenafly",
    category: "Animals",
    description:
      "Help care for foster dogs, assist at adoption events, transport animals, or support fundraising for this all-volunteer dog rescue.",
    ageDisplay: "Age varies; mostly high school students and adults",
    minimumAge: null,
    requirements: ["Fill out form"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.petresqinc.org/volunteer",
    applicationUrl: null,
    notes: ["Needs verification"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "High school", "Animal rescue"]
  },
  {
    id: "korean-community-center",
    organization: "Korean Community Center",
    town: "Tenafly",
    category: "Community Services",
    description:
      "Volunteer with senior programs, tutoring, cultural events, administrative support, and community outreach programs.",
    ageDisplay: "High school students grades 9-12 for the summer camp teacher's assistant",
    minimumAge: null,
    requirements: ["Fill out form to apply", "Contact number or email"],
    schedule: ["Summer camp teacher's assistant"],
    volunteerUrl: "https://www.kcsus.org/volunteer",
    applicationUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdchUj9KtFV7aVGerbuprBp2bO8cOHABpkTuAoq8qVbYeECdg/viewform",
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Grades 9-12", "Summer camp", "Form"]
  },
  {
    id: "center-for-food-action-englewood",
    organization: "Center for Food Action",
    town: "Englewood",
    category: "Food Assistance",
    description:
      "Help sort food, pack boxes, distribute groceries, work in the organic garden, or assist with warehouse and administrative tasks. Community service hours are available.",
    ageDisplay: "Under 18 with parent signature; 16+",
    minimumAge: 16,
    requirements: ["Under 18 requires parent signature", "Apply through form"],
    schedule: ["At least one 2-3 hour shift per week", "9:45 AM - 12:00 PM", "Weekends not available"],
    volunteerUrl: "https://cfanj.org/volunteer/",
    applicationUrl: null,
    notes: ["Different other locations"],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 16+", "Parent signature", "2-3 hours/week", "No weekends"]
  },
  {
    id: "office-of-concern-food-pantry",
    organization: "Office of Concern Food Pantry",
    town: "Englewood",
    category: "Food Assistance",
    description:
      "Help sort donations, organize food, assist families during distribution, and support food drives. Student volunteers are especially welcome during school breaks.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Call them to volunteer"],
    schedule: ["Monday through Wednesday, 9 AM - 12 PM"],
    volunteerUrl: "https://www.officeofconcern.com/volunteer",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "School breaks", "Food pantry"]
  },
  {
    id: "bergen-family-center",
    organization: "Bergen Family Center",
    town: "Englewood",
    category: "Social Services",
    description:
      "Volunteer with after-school programs, tutoring, family support services, and community events that benefit children and families.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact organization"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://bergenfamilycenter.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Tutoring", "Family support"]
  },
  {
    id: "start-ii-animal-rescue",
    organization: "START II Animal Rescue",
    town: "Englewood",
    category: "Animals",
    description:
      "Care for dogs and cats, clean kennels, walk dogs, assist with adoption events, and help with fundraising.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them to join"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://sites.google.com/view/save-the-animals-rescue-team-2/get-involved",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Animal rescue", "Adoption events"]
  },
  {
    id: "bergen-hatzalah",
    organization: "Bergen Hatzalah",
    town: "Englewood",
    category: "Healthcare",
    description:
      "Join a volunteer emergency medical service providing rapid EMS response throughout Bergen County.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Email them to get involved"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://bergenhatzalah.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "EMS", "Email"]
  },
  {
    id: "englewood-public-library-friends",
    organization: "Englewood Public Library / Friends of the Library",
    town: "Englewood",
    category: "Library",
    description:
      "Support library programs, book sales, children's events, and community programming through the Friends of the Library.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: [
      "Join the Friends and volunteer in the book room, community special events, or membership committee"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://englewoodlibrary.org/friends-of-the-library/",
    applicationUrl: "https://englewoodlibrary.org/wp-content/uploads/2025/07/FriendsMembership-2025-07-2.pdf",
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age varies", "Friends", "PDF form"]
  },
  {
    id: "alpine-volunteer-fire-department",
    organization: "Alpine Volunteer Fire Department",
    town: "Alpine",
    category: "Public Safety",
    description:
      "Volunteer firefighters help protect Alpine by responding to fires, emergencies, and public safety incidents. Training is provided for new members.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them to join"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.alpinenj.gov/page/alpine-fire-dept",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Training", "Contact organization"]
  },
  {
    id: "alpine-swim-club",
    organization: "Alpine Swim Club",
    town: "Alpine",
    category: "Recreation",
    description:
      "Volunteers help support the Alpine Swim Club and seasonal community programs. Certified lifeguards are also recruited each season.",
    ageDisplay: "Age varies; under 18 may volunteer with working papers",
    minimumAge: null,
    requirements: ["Contact them", "Under 18 may volunteer with working papers"],
    schedule: ["Seasonal and includes both volunteer support and paid lifeguard roles"],
    volunteerUrl: "https://www.alpinenj.gov/page/alpine-swim-club",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age varies", "Working papers", "Seasonal"]
  },
  {
    id: "church-of-the-lord",
    organization: "Church of the Lord",
    town: "Alpine",
    category: "Faith-Based",
    description:
      "Volunteers help with church events, youth programs, meal preparation, and community outreach throughout the year.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact the church to volunteer"],
    schedule: ["Throughout the year"],
    volunteerUrl: "https://www.churchofthelord.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Ongoing",
    needsVerification: true,
    tags: ["Age varies", "Church events", "Outreach"]
  },
  {
    id: "rockleigh-volunteer-fire-department",
    organization: "Rockleigh Volunteer Fire Department",
    town: "Rockleigh",
    category: "Public Safety",
    description:
      "Volunteer firefighters respond to fires and emergencies while protecting the borough through training and emergency response.",
    ageDisplay: "Contact department for volunteering and age",
    minimumAge: null,
    requirements: ["Contact department for volunteering and age"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.rockleighnj.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Training", "Contact department"]
  },
  {
    id: "northern-valley-rotary-club-rockleigh",
    organization: "Northern Valley Rotary Club",
    town: "Rockleigh",
    category: "Community Services",
    description:
      "Volunteers participate in community service projects, fundraisers, scholarship initiatives, and charitable events benefiting the Northern Valley area.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact the borough directly"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.rockleighnj.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Fundraisers", "Community service"]
  },
  {
    id: "westwood-public-library",
    organization: "Westwood Public Library",
    town: "Westwood",
    category: "Library",
    description:
      "Help with children's programs, technology assistance, shelving books, library events, and community projects. Volunteer openings vary throughout the year.",
    ageDisplay: "Age varies; tweens, teens, and adults",
    minimumAge: null,
    requirements: ["Tweens and teens apply via application for various roles"],
    schedule: ["Volunteer openings vary throughout the year"],
    volunteerUrl: "https://westwoodlibrary.org/volunteer/",
    applicationUrl: null,
    notes: ["Adult volunteer information is on the same volunteer page"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age varies", "Tweens", "Teens"]
  },
  {
    id: "junior-friends-of-westwood-public-library",
    organization: "Junior Friends of Westwood Public Library",
    town: "Westwood",
    category: "Library",
    description:
      "Earn community service hours by helping with library programs, craft preparation, organizing materials, book reviews, and monthly volunteer projects.",
    ageDisplay: "7th grade and up",
    minimumAge: null,
    requirements: [],
    schedule: ["Monthly volunteer projects"],
    volunteerUrl: "https://www.westwoodpubliclibrary.org/junior-friends-of-the-westwood-public-library",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["7th grade+", "Community service hours", "Monthly projects"]
  },
  {
    id: "friends-of-the-westwood-public-library",
    organization: "Friends of the Westwood Public Library",
    town: "Westwood",
    category: "Library",
    description:
      "Volunteer at monthly book sales, sort donated books, assist with fundraising events, and support library programs.",
    ageDisplay: "Age varies; older teens and adults",
    minimumAge: null,
    requirements: [],
    schedule: ["Monthly book sales"],
    volunteerUrl: "https://www.westwoodpubliclibrary.org/friends-of-the-westwood-public-library",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age varies", "Older teens", "Book sales"]
  },
  {
    id: "westwood-volunteer-ambulance-corps",
    organization: "Westwood Volunteer Ambulance Corps",
    town: "Westwood",
    category: "Healthcare",
    description:
      "Volunteer with the ambulance corps and help provide emergency medical service to the Westwood community.",
    ageDisplay: "16+",
    minimumAge: 16,
    requirements: [
      "Resides in Westwood, works in Westwood, or lives within a 3 mile radius of the building",
      "Download the application and complete it, then send it to the recruiting committee chairperson"
    ],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.westwoodvolunteerems.org/join.html",
    applicationUrl: null,
    notes: ["Application is downloaded from the volunteer page"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 16+", "3 mile radius", "Download application"]
  },
  {
    id: "westwood-volunteer-fire-department",
    organization: "Westwood Volunteer Fire Department",
    town: "Westwood",
    category: "Public Safety",
    description:
      "Join the Cadet Corps or become a volunteer firefighter. Training is provided, and the department actively recruits new members.",
    ageDisplay: "Cadets 15-17; firefighters 18+",
    minimumAge: 15,
    requirements: ["Call or stop by"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.westwoodfire.org/join-the-wfd",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 15+", "Cadets", "Firefighters 18+", "Training"]
  },
  {
    id: "peace-4-paws",
    organization: "Peace 4 Paws",
    town: "Westwood",
    category: "Animals",
    description:
      "Help foster dogs, assist with adoption events, fundraising, transportation, and community outreach. This is a volunteer-run animal rescue.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact"],
    schedule: ["May volunteer to walk dogs"],
    volunteerUrl: "https://peace4paws.org/",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Animal rescue", "Walk dogs"]
  },
  {
    id: "westwood-borough-community-volunteering",
    organization: "Westwood Borough Community Volunteering",
    town: "Westwood",
    category: "Civic",
    description:
      "Volunteer on borough boards, committees, emergency service organizations, or community programs by submitting the borough's volunteer form.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Submit the borough's community volunteer form"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.westwoodnj.gov/276/Volunteering",
    applicationUrl: "https://www.westwoodnj.gov/DocumentCenter/View/662/Community-Volunteer-Form-PDF",
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 18+", "Boards", "Committees", "Form"]
  },
  {
    id: "teaneck-public-library",
    organization: "Teaneck Public Library",
    town: "Teaneck",
    category: "Library",
    description:
      "Volunteer through the Teen Volunteer Program, Teen Advisory Board, Craft Helpers, Adopt-a-Shelf, book reviews, media reviews, and library events. Great for earning community service hours.",
    ageDisplay: "Grades 7-12",
    minimumAge: null,
    requirements: ["Apply using the teen volunteer application form"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://teanecklibrary.org/teens/teen-volunteer/",
    applicationUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdagyI-ZSMAt6wxhWpM-os4Ln9ZbaJklm4pX60Gun6zOJHZqA/viewform",
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Grades 7-12", "Teen Advisory Board", "Community service hours"]
  },
  {
    id: "teaneck-volunteer-ambulance-corps",
    organization: "Teaneck Volunteer Ambulance Corps",
    town: "Teaneck",
    category: "Healthcare",
    description:
      "Volunteer as an EMT or support member with Teaneck's nonprofit ambulance corps. Training is provided.",
    ageDisplay:
      "Age 15.5+ for full members; active EMT role is 18+; associate member age varies",
    minimumAge: 15.5,
    requirements: [
      "Be an EMT or commit to becoming one within 12 months of joining",
      "Able to pass a background check if over 18",
      "Active member",
      "EMT",
      "Associate member"
    ],
    schedule: ["4 hour shift per week", "Two 12 hour Sunday shifts per year", "Part time"],
    volunteerUrl: "https://www.teaneckambulance.org/contact--apply.html",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: true,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 15.5+", "EMT", "Training", "Sunday shifts"]
  },
  {
    id: "holy-name-medical-center",
    organization: "Holy Name Medical Center",
    town: "Teaneck",
    category: "Healthcare",
    description:
      "The Department of Volunteer Services brings together a diverse group of women, men, and teenagers dedicated to supporting patients, families, staff, and visitors with compassion, courtesy, and exceptional service. Volunteers receive training for their roles and can choose from over 100 opportunities throughout the Medical Center - no prior experience is required. With meaningful ways to give back and make a difference every day, there's a place for everyone on the team.",
    ageDisplay: "Age 16-18 for junior volunteers; college and adult programs available",
    minimumAge: 16,
    requirements: [
      "Volunteer adult program",
      "College volunteer opportunity",
      "Junior volunteer program",
      "College volunteers have the same credentials as adult volunteers",
      "Shadowing physicians"
    ],
    schedule: [
      "Adult program requires 75 service hours per year minimum",
      "Monday-Friday for 4 hour shifts",
      "Junior volunteer program requires 6 months and 75 hours"
    ],
    volunteerUrl: "https://www.holyname.org/Volunteer/index.aspx",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 16+", "Grades 9-12", "Training", "75 hours"]
  },
  {
    id: "helping-hand-food-pantry",
    organization: "Helping Hand Food Pantry",
    town: "Teaneck",
    category: "Food Assistance",
    description:
      "Help distribute food, organize donations, and support local families. The pantry actively welcomes volunteers.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Contact them and fill out form"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://teaneckpantry.com/volunteer-inquiry",
    applicationUrl: null,
    notes: ["Needs verification: age not listed"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Food pantry", "Volunteer inquiry"]
  },
  {
    id: "teaneck-public-schools",
    organization: "Teaneck Public Schools",
    town: "Teaneck",
    category: "Education",
    description:
      "Volunteer as a reading buddy, tutor, mentor, classroom helper, or library assistant after completing training and a background check.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Training", "Background check"],
    schedule: ["Regularly or just a few times a year"],
    volunteerUrl: "https://www.teaneckschools.org/Volunteers.aspx",
    applicationUrl: null,
    notes: ["Adults and community members"],
    teenFriendly: false,
    weekend: false,
    duration: "One-time and ongoing",
    needsVerification: false,
    tags: ["Age 18+", "Tutoring", "Background check"]
  },
  {
    id: "never-alone-again-resource-center",
    organization: "Never Alone Again Resource Center",
    town: "Teaneck",
    category: "Social Services",
    description:
      "Help distribute clothing and essentials to families in need. Student volunteers can earn community service hours.",
    ageDisplay: "Age varies; students and adults",
    minimumAge: null,
    requirements: ["Sign up and apply"],
    schedule: ["Contact organization"],
    volunteerUrl: null,
    applicationUrl: "https://charityquest.io/questList/19159AB512A5D4B9",
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age varies", "Students", "Community service hours"]
  },
  {
    id: "hackensack-university-medical-center",
    organization: "Hackensack University Medical Center",
    town: "Hackensack",
    category: "Healthcare",
    description:
      "Volunteers are expected to interact respectfully with patients, visitors, physicians, and staff while completing required training, wearing the provided uniform, and working effectively as part of a team.",
    ageDisplay: "Age 16+",
    minimumAge: 16,
    requirements: [
      "Complete required training",
      "Wear the provided uniform",
      "Work effectively as part of a team"
    ],
    schedule: ["Commit 4 hours a week", "80 hours per year"],
    volunteerUrl: "https://www.hackensackmeridianhealth.org/en/patients-and-visitors/volunteer-program",
    applicationUrl: null,
    notes: [],
    teenFriendly: true,
    weekend: false,
    duration: "Ongoing",
    needsVerification: false,
    tags: ["Age 16+", "Training", "4 hours/week", "80 hours/year"]
  },
  {
    id: "johnson-public-library",
    organization: "Johnson Public Library",
    town: "Hackensack",
    category: "Library",
    description:
      "Assist with children's events, shelving, library programs, and community activities. Contact the library for volunteer opportunities and apply using the form.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Apply through city of Johnson form"],
    schedule: ["Contact organization"],
    volunteerUrl: null,
    applicationUrl: "https://www.cityofjohnston.com/FormCenter/Library-5/Adult-Volunteer-Application-Ages-18-93",
    notes: ["Needs verification: source says city of Johnson/Johnston form"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 18+", "Library events", "Application form"]
  },
  {
    id: "bergen-county-animal-shelter",
    organization: "Bergen County Animal Shelter",
    town: "Hackensack",
    category: "Animals",
    description:
      "Care for animals, help with adoption events, walking dogs, and cleaning kennels.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: [],
    schedule: ["Contact organization"],
    volunteerUrl: "https://bergencountynj.gov/bergen-county-department-of-health-services/about-animal-shelter-adoption-center/volunteer-opportunities/",
    applicationUrl: "https://bergencountynj.gov/wp-content/uploads/2025/06/Volunteer-App-6-11-25.pdf",
    notes: [],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age 18+", "Animal shelter", "Application PDF"]
  },
  {
    id: "meals-on-wheels-north-jersey",
    organization: "Meals on Wheels North Jersey",
    town: "Hackensack",
    category: "Food Assistance",
    description:
      "Deliver meals and assist seniors throughout Bergen County.",
    ageDisplay: "Age 18+",
    minimumAge: 18,
    requirements: ["Search volunteer opportunities"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.mealsonwheelsamerica.org/volunteer/",
    applicationUrl: null,
    notes: ["Needs verification: source listed mostly adults"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age 18+", "Seniors", "Meal delivery"]
  },
  {
    id: "habitat-for-humanity-of-bergen-county",
    organization: "Habitat for Humanity of Bergen County",
    town: "Hackensack",
    category: "Housing",
    description:
      "Help build and repair homes, organize donations, and support fundraising events.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Apply through application and choose a nearby town"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.habitat.org/volunteer",
    applicationUrl: null,
    notes: ["Hackensack, Westwood, and more"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Housing", "Nearby towns"]
  },
  {
    id: "englewood-cliffs-recreation-department",
    organization: "Englewood Cliffs Recreation Department",
    town: "Englewood Cliffs",
    category: "Recreation",
    description:
      "Volunteer as a coach or helper for recreation programs and community events. Background checks are required.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Reach out via email", "Background checks are required"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://englewoodcliffsnj.org/departments/parks_recreation/volunteer.php",
    applicationUrl: null,
    notes: ["Contact organization"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Coach", "Background check"]
  },
  {
    id: "englewood-cliffs-volunteer-fire-department",
    organization: "Englewood Cliffs Volunteer Fire Department",
    town: "Englewood Cliffs",
    category: "Public Safety",
    description:
      "Volunteer firefighters respond to emergencies and participate in training and community outreach.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["Fill out form", "Contact department for age"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.englewoodcliffsfd.org/join",
    applicationUrl: null,
    notes: ["Needs verification: age not mentioned"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Training", "Form"]
  },
  {
    id: "englewood-cliffs-public-library",
    organization: "Englewood Cliffs Public Library",
    town: "Englewood Cliffs",
    category: "Library",
    description:
      "Help with children's activities, library events, and community programs when volunteer positions are available.",
    ageDisplay: "Age varies",
    minimumAge: null,
    requirements: ["To join, fill out the form", "Contact library for age"],
    schedule: ["Volunteer positions vary"],
    volunteerUrl: "https://englewoodlibrary.org/friends-of-the-library/",
    applicationUrl: null,
    notes: ["Needs verification: source says most likely adult"],
    teenFriendly: false,
    weekend: false,
    duration: "Contact organization",
    needsVerification: true,
    tags: ["Age varies", "Library events", "Form"]
  },
  {
    id: "flat-rock-brook-nature-center",
    organization: "Flat Rock Brook Nature Center",
    town: "Englewood Cliffs",
    category: "Environment",
    description:
      "Volunteer with trail maintenance, environmental education, habitat restoration, and special events.",
    ageDisplay: "Age varies; students and adults",
    minimumAge: null,
    requirements: ["Fill out form"],
    schedule: ["Contact organization"],
    volunteerUrl: "https://www.flatrockbrook.org/volunteer",
    applicationUrl: null,
    notes: ["Very close to Englewood Cliffs"],
    teenFriendly: true,
    weekend: false,
    duration: "Contact organization",
    needsVerification: false,
    tags: ["Age varies", "Students", "Trail maintenance", "Habitat restoration"]
  }
];

export function getOpportunity(id: string) {
  return opportunities.find((opportunity) => opportunity.id === id);
}

export const towns = Array.from(
  new Set(opportunities.map((opportunity) => opportunity.town))
).sort();

export const categories = Array.from(
  new Set(opportunities.map((opportunity) => opportunity.category))
).sort();
